Update patch set 1
Patch Set 1: Workflow-1

from neutron.conf.plugins.ml2 import config
ImportError: cannot import name config

That looks like change on networking-fujitsu master branch which is incompatible with Pike neutron and there isn't stable/pike branch?

Patch-set: 1
Label: Workflow=-1